---
# Template configuration files for syslog

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ syslog_templates_copy }}"
  when: syslog_copy_templates
